### ISSUE TITLE
take minimap into account for centering

### ISSUE THREAD

**Issue by braver** [braver/typewriter#1]
two approaches come to mind:
1. take minimap out of the flow and position it on top of the editing area.
   downsides:
2. if screen is too small stuff overlaps

![screen shot 2015-04-01 at 17 06 30](https://cloud.githubusercontent.com/assets/2543659/6944841/4a8b6420-d896-11e4-934c-2760cdc99fba.png)
1. measure the width of the minimap and add it as padding to the left
   downsides:
2. minimap might build later and we need to wait for that, causing the editor to jump sideways
3. kills the neat css based layout we had

**Comment by Fironet** [comment]
I noticed this package centers the minimap, is there a way of disabling this behavior so it's like Sublime Text where the minimap is always on the very edge (right) of the screen?

Being able to quickly move the cursor to the edge of the screen for scrolling is one of the main benefits of the minimap (and scrollbar to a lesser extent).

**Comment by braver** [comment]
Could be, but that's not necessarily easy. Open a PR if you have ideas!
