### ISSUE TITLE
Code & todo syntax support?

### ISSUE THREAD

**Issue by orschiro** [braver/typewriter#10]
Dear @braver,

I noticed that code & todo syntax support is disabled by typewriter although Atom itself supports it. Would it be somehow possible to turn on both?

Thankfully,

Robert

**Code syntax support:**
![](http://i.imgur.com/LSRfim1.png)

**TODO syntax support:**
![](http://i.imgur.com/gUZEljQ.png)

**Comment by braver** [comment]
Typewriter is basically just a layout stylesheet, it doesn't touch syntax or anything else inside the editor. Can you show a screenshot with and without Typewriter enabled?

**Comment by orschiro** [comment]
Dear @braver,

I think you are right. It does not seem to be a problem of Typewriter at all because disabling it does not bring TODO syntax highlighting. 

I apologise for the irritation. I will further investigate the issue and report back once I have found the cause. 

~ Robert

**Comment by braver** [comment]
Cool :+1:

**Comment by orschiro** [comment]
The solution was simple. The todo plugin doesn't actually support `.md` files but only `.txt` extensions...
