### ISSUE TITLE
Scroll bar in a wrong place?

### ISSUE THREAD

**Issue by kmisiunas** [braver/typewriter#19]
Thanks for developing this! I feel that scroll bar should be on the rightmost place. However, I find it just after the text field:

![screen shot 2017-02-22 at 13 12 23](https://cloud.githubusercontent.com/assets/4820843/23212930/d5ebf4da-f900-11e6-84fd-79ca647f7ca5.png)

**Comment by braver** [comment]
As far as I could tell it can't be helped because of the way the editor is structured. You could also hide the scrollbar, that helps.

**Comment by iCodeForBananas** [comment]
I think you're right but would require a lot of work.  
Probably not going to see this anytime soon though unless someone submits a PR that fixes it.
