### ISSUE TITLE
don't force soft-wrap for everything

### ISSUE THREAD

**Issue by braver** [braver/typewriter#2]
it might be possible to force soft-wrap just for markdown

**Comment by dsandstrom** [comment]
:+1:

**Comment by dsandstrom** [comment]
If not possible, maybe make the soft-wrap optional.  Then let us control the soft-wrap setting via language settings.

**Comment by braver** [comment]
@dsandstrom it's possible to set it only for certain scopes, I just found [the docs describing how to do this](https://atom.io/docs/v0.189.0/behind-atom-scoped-settings-scopes-and-scope-descriptors). So I'll just force it for markdown and wiki.

**Comment by braver** [comment]
0.2.0 sets softWrap just for the specific scopes.
