### ISSUE TITLE
Volunteering as a maintainer!

### ISSUE THREAD

**Issue by iCodeForBananas** [braver/typewriter#22]
I plan on using this plugin quite a bit and would be honored to maintain it's code base! :)

This will be my first time maintaining a package for Atom so I might have a few questions.  Working on the code base won't be an issue though.

**Comment by braver** [comment]
Awesome! You should have mail about this.

Two points of review based on your last PR:
- be careful not to commit `console.log` messages
- I think this package is most useful for "writing", so it makes sense to default to whitelisting specific scopes

Anyway, thanks for the effort, have fun with it, and if you have any questions let me know!
