### ISSUE TITLE
Documentation: configure line width for soft wrapping

### ISSUE THREAD

**Issue by michaelstepner** [braver/typewriter#24]
After I installed `typewriter` I searched for a way to configure it to show a wider width.  For example, [Zen](https://github.com/defunkt/Zen) provides a config setting for width.  I was initially disappointed to see that `typewriter` has no such option.

After inspecting the code, I see that `typewriter` actually takes the width from Atom's general settings under `Settings > Editor > Preferred Line Length`.  That seems quite reasonable.  But it would be better if a new user could learn this more easily.  I'd suggest:

1. Document how to set the width in the README
2. *Optionally,* provide a plugin config setting to override the global "Preferred Line Length" setting, as Zen does.

That second feature isn't helpful for me: I'm happy to have a global setting for preferred line length.  But perhaps others out there would prefer to be able to configure the line length for `typewriter` separately.

**Comment by iCodeForBananas** [comment]
I added something to the `README` about this.  Thanks for the heads up!
