### ISSUE TITLE
Update README on atom.io

### ISSUE THREAD

**Issue by michaelstepner** [braver/typewriter#25]
The readme on the [atom.io typewriter page](https://atom.io/packages/typewriter) is out of date compared to the [Github readme](https://github.com/braver/typewriter/blob/master/README.md).

**Comment by iCodeForBananas** [comment]
@braver Is there a chance you could update the Atom package or send me a link to how you do it?

**Comment by braver** [comment]
@michaeljcalkins I think you may have made a tag from within Github. Confusingly, that's not enough: the tag needs to be registered with apm (atom package manager). Assuming you already have apm installed, from your clone of the repo you run `apm publish minor` to publish a 0.x.0 version with apm. This also creates a tag, which might conflict with existing tags, but that's the basic mechanism.
