### ISSUE TITLE
Package permanently turns on soft wrap in config file

### ISSUE THREAD

**Issue by maxbrunsfeld** [braver/typewriter#27]
This package permanently enables soft wrap for certain scopes. Instead, I'd advise calling `editor.setSoftWrapped(true)` in order to enable soft wrap for a particular editor.

**Comment by kasparsd** [comment]
@maxbrunsfeld Does #28 look right?

**Comment by maxbrunsfeld** [comment]
Yes!

**Comment by kasparsd** [comment]
Thanks for the confirmation @maxbrunsfeld!

@braver I was wondering if you could look into merging #28 which should resolve this issue. Thanks!

**Comment by braver** [comment]
Done! Thanks guys.
