### ISSUE TITLE
Add option for other syntaxes

### ISSUE THREAD

**Issue by dsandstrom** [braver/typewriter#3]
I was working on a [wiki](https://atom.io/packages/language-mediawiki) page and thought it would be cool to use this package.

**Comment by braver** [comment]
great suggestion, I'm looking into it right now

**Comment by braver** [comment]
wiki has just been added in 0.2.0. I'm looking into allowing you to define your own scopes for this, so I'm keeping this issue open for that.

**Comment by braver** [comment]
Look out for the next release for the ability to add any scope!
