### ISSUE TITLE
Soft wrap width doesn't match hard wrap (autoflow)

### ISSUE THREAD

**Issue by tpoisot** [braver/typewriter#6]
Thanks for the package, It's **awesome**.

One thing that would make it awesomer is to keep the line wrapping when saving. My usual workflow is
1. write something
2. commit and push to a git repo
3. look at the diff later on to see what changed

Having wrapped lines in the diff makes it easier to see what changed. Is this an option that can be added?

**Comment by braver** [comment]
I'm glad you enjoy the package :) Right now, typewriter uses the soft wrap feature in Atom, which means the wrap is only visual and not stored in any way. I can see how "hard" wrap would be beneficial in your workflow. Long paragraphs don't diff well in most tools and certainly not in simple text editor diffs.

I could look for something that provides hard wrap functionality and work with that. I'll look into it!

**Comment by braver** [comment]
One thing you could do is work [autoflow](https://atom.io/packages/autoflow) into your workflow. I think I could write something that could automate that (on key-up or something), but not as part of typewriter. @leedohm had plans of doing something like that as well, don't think it happened yet. I'll put it on my list of plans!

**Comment by tpoisot** [comment]
This is what I thought of doing, but for some reason, calling autoflow messes up the lines when used with typewriter:

![capture d ecran de 2015-05-04 15-04-21](https://cloud.githubusercontent.com/assets/579329/7460132/e8a47d76-f26e-11e4-9378-ba8574806315.png)

**Comment by braver** [comment]
Actually, that does look like a bug. It seems I need another 15px on the editor to make the lines match the width. If I add 15px it seems to work just fine along with autoflow. I'll try and fix that, if I can find out where those pixels come from.

**Comment by tpoisot** [comment]
Could it be the width of the scrollbar?

**Comment by braver** [comment]
Yes, that's probably it. Darn.

**Comment by braver** [comment]
I looked into it and it's not going to happen if I have to code this: I can't find a reliable hook to fix this on.
