### ISSUE TITLE
Setting for enabling / disabling features

### ISSUE THREAD

**Issue by Meligy** [braver/typewriter#8]
Can we turn all the main features in readme 
- Centered layout
- No gutter
- No scrollbar (unless you hover over the editor)
- Enables soft-wrapping for selected scopes

into settings checkboxes?

my personal use case is that I might actually want to keep the gutter (I like to look at line numbers, and I use another plugin that folds headers in markdown).

Thanks a lot.

**Comment by braver** [comment]
Sure, that should be possible, easy even. I don't have the time to look into it now, but if you send in a PR ... :)

**Comment by braver** [comment]
fixed in [0.6.0](https://github.com/braver/typewriter/releases/tag/v0.6.0)
