### ISSUE TITLE
Hide single tab

### ISSUE THREAD

**Issue by orschiro** [braver/typewriter#9]
Dear @braver,

Thank you very much for your package! It greatly enhances my Markdown writing experience. I have one question. 

Would it be possible to add a setting that auto-hides the tab bar if there is only one tab open?

Thankfully,

Robert

![markdown-typewriter-single-tab](https://cloud.githubusercontent.com/assets/170947/10129085/92a826ce-65ba-11e5-8fe1-b82fab95a118.png)

**Comment by braver** [comment]
Hi @orschiro, I'm glad you enjoy it. I'm not 100% sure about this, it kind of goes against the simplicity of the package. There doesn't seem to be an easy hook for this either. It should be possible to add something to your init file to do something like this though...

**Comment by orschiro** [comment]
Dear @braver,

I can follow your reasoning. Thanks for taking your time!

Robert
